### ISSUE TITLE
Feature request: Expand macro recursively

### ISSUE THREAD

**Issue by edwloef** [neurocyte/flow#88] opened 2024-12-21 13:49 UTC
I'm not sure whether this is useful in many languages besides rust, but seeing macro-expanded code can be useful at times. Having an editor command/action to do this with the macro the cursor currently resides in would be useful.

This is how Zed does it:

https://github.com/user-attachments/assets/46f6a035-6491-40b6-8cc1-2bf051ffcf7a

**Comment by neurocyte** [comment] 2024-12-21 15:43
From what I can tell this feature is just a wrapper around `cargo expand {function name}`. If so, I'd say this could be marked a duplicate of #67. The shell command should be specified to include a way to send the current selection (or word-at-cursor) to the shell command and also a way to specify that the output should be sent to a new buffer (and allow specifying the language).

**Closed by neurocyte** 2024-12-21 15:43 UTC
Labels: enhancement
